syntax = "proto3";

package syncserver;

import "google/protobuf/empty.proto";

message DocumentIDRequest {
    uint64 id = 1;
}

message PermissionChangedRequest {
    uint64 doc_id = 1;
    uint64 user_id = 2;
    string role = 3;
}

service SyncServerInternal {
    rpc PostSnapshot(DocumentIDRequest) returns (google.protobuf.Empty) {}
    rpc DeleteDocument(DocumentIDRequest) returns (google.protobuf.Empty) {}
    rpc PermissionChanged(PermissionChangedRequest) returns (google.protobuf.Empty) {}
}